// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectBase.Helpers;

#nullable disable

namespace ProjectBase.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260730174523_LinkPracticeToSimulationExam")]
    partial class LinkPracticeToSimulationExam
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectBase.Models.BlogsModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("blog_picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("link_media")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("publishAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("ProjectBase.Models.Blogs_CategoryModel", b =>
                {
                    b.Property<long>("BlogID")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.ToTable("Blogs_Category");
                });

            modelBuilder.Entity("ProjectBase.Models.CategoryModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("ProjectBase.Models.DAO.User", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("ID"));

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RoleID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VerificationTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("gender")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("profile_picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("register_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.Property<string>("verificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectBase.Models.PracticeLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PracticeLevel");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Easy",
                            title = "Easy"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Medium",
                            title = "Medium"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Hard",
                            title = "Hard"
                        });
                });

            modelBuilder.Entity("ProjectBase.Models.PracticeModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Quest_group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SimulationExamID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<long>("SubjectID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<TimeOnly>("duration")
                        .HasColumnType("time");

                    b.Property<int>("levelID")
                        .HasColumnType("int");

                    b.Property<int>("number_correct")
                        .HasColumnType("int");

                    b.Property<int>("number_quest")
                        .HasColumnType("int");

                    b.Property<DateTime>("taken_date")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("time_taken")
                        .HasColumnType("time");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("topicID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SimulationExamID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("UserID");

                    b.HasIndex("levelID");

                    b.HasIndex("topicID");

                    b.ToTable("Practice");
                });

            modelBuilder.Entity("ProjectBase.Models.PricePackageModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("ListPrice")
                        .HasColumnType("bigint");

                    b.Property<long>("PackageType")
                        .HasColumnType("bigint");

                    b.Property<long>("SalePrice")
                        .HasColumnType("bigint");

                    b.Property<long>("SubjectID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Price_package");
                });

            modelBuilder.Entity("ProjectBase.Models.QuizBankModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("GroupID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.Property<string>("QA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qcorrect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<long>("SubjectID")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("QuizBank");
                });

            modelBuilder.Entity("ProjectBase.Models.QuizHandleModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("PracticeID")
                        .HasColumnType("bigint");

                    b.Property<string>("QAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("QuizID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.Property<bool>("isCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("isMark")
                        .HasColumnType("bit");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("QuizID");

                    b.ToTable("QuizHandle");
                });

            modelBuilder.Entity("ProjectBase.Models.RecipeModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime>("BuyAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PricePackage_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("PricePackage_Type")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SubjectID")
                        .HasColumnType("bigint");

                    b.Property<long>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PricePackage_ID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("UserID");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("ProjectBase.Models.SimulationExam", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelID")
                        .HasColumnType("int");

                    b.Property<int>("Number_Question")
                        .HasColumnType("int");

                    b.Property<decimal>("Passrate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("SubjectID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("LevelID");

                    b.HasIndex("SubjectID");

                    b.ToTable("SimulationExam");
                });

            modelBuilder.Entity("ProjectBase.Models.SliderModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("backlink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("publishAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("userID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("userID");

                    b.ToTable("Slider");
                });

            modelBuilder.Entity("ProjectBase.Models.SubjectTopicModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("subjectId")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SubjectTopic");

                    b.HasData(
                        new
                        {
                            id = 1,
                            subjectId = 0L,
                            title = "General"
                        });
                });

            modelBuilder.Entity("ProjectBase.Models.Subject_CategoryModel", b =>
                {
                    b.Property<long>("SubjectID")
                        .HasColumnType("bigint");

                    b.Property<long>("CategoryID")
                        .HasColumnType("bigint");

                    b.HasKey("SubjectID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Subject_Category");
                });

            modelBuilder.Entity("ProjectBase.Models.SubjectsModel", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.Property<string>("brief_info")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isHot")
                        .HasColumnType("bit");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.Property<DateTime?>("registerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("thumbnail_color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<long>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleID = 1L,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2L,
                            RoleName = "Customer"
                        },
                        new
                        {
                            RoleID = 3L,
                            RoleName = "Marketing"
                        },
                        new
                        {
                            RoleID = 4L,
                            RoleName = "Sale"
                        },
                        new
                        {
                            RoleID = 5L,
                            RoleName = "Expert"
                        },
                        new
                        {
                            RoleID = 6L,
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("ProjectBase.Models.DAO.User", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProjectBase.Models.PracticeModel", b =>
                {
                    b.HasOne("ProjectBase.Models.SimulationExam", "SimulationExam")
                        .WithMany()
                        .HasForeignKey("SimulationExamID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ProjectBase.Models.SubjectsModel", "Subject")
                        .WithMany("Practice")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBase.Models.DAO.User", "User")
                        .WithMany("Practice")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBase.Models.PracticeLevel", "Level")
                        .WithMany("Practice")
                        .HasForeignKey("levelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBase.Models.SubjectTopicModel", "Topic")
                        .WithMany("Practice")
                        .HasForeignKey("topicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("SimulationExam");

                    b.Navigation("Subject");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectBase.Models.PricePackageModel", b =>
                {
                    b.HasOne("ProjectBase.Models.SubjectsModel", "Subjects")
                        .WithMany("Price_package")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ProjectBase.Models.QuizHandleModel", b =>
                {
                    b.HasOne("ProjectBase.Models.QuizBankModel", "QuizBank")
                        .WithMany("QuizHandle")
                        .HasForeignKey("QuizID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizBank");
                });

            modelBuilder.Entity("ProjectBase.Models.RecipeModel", b =>
                {
                    b.HasOne("ProjectBase.Models.PricePackageModel", "PricePackage")
                        .WithMany("Recipe")
                        .HasForeignKey("PricePackage_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBase.Models.SubjectsModel", "Subjects")
                        .WithMany("Recipes")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBase.Models.DAO.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricePackage");

                    b.Navigation("Subjects");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectBase.Models.SimulationExam", b =>
                {
                    b.HasOne("ProjectBase.Models.PracticeLevel", "Level")
                        .WithMany("Exams")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBase.Models.SubjectsModel", "Subjects")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Level");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ProjectBase.Models.SliderModel", b =>
                {
                    b.HasOne("ProjectBase.Models.DAO.User", "User")
                        .WithMany("Sliders")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectBase.Models.Subject_CategoryModel", b =>
                {
                    b.HasOne("ProjectBase.Models.CategoryModel", "Category")
                        .WithMany("Subject_Category")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBase.Models.SubjectsModel", "Subjects")
                        .WithMany("Subject_Category")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ProjectBase.Models.CategoryModel", b =>
                {
                    b.Navigation("Subject_Category");
                });

            modelBuilder.Entity("ProjectBase.Models.DAO.User", b =>
                {
                    b.Navigation("Practice");

                    b.Navigation("Recipes");

                    b.Navigation("Sliders");
                });

            modelBuilder.Entity("ProjectBase.Models.PracticeLevel", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Practice");
                });

            modelBuilder.Entity("ProjectBase.Models.PricePackageModel", b =>
                {
                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ProjectBase.Models.QuizBankModel", b =>
                {
                    b.Navigation("QuizHandle");
                });

            modelBuilder.Entity("ProjectBase.Models.SubjectTopicModel", b =>
                {
                    b.Navigation("Practice");
                });

            modelBuilder.Entity("ProjectBase.Models.SubjectsModel", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("Practice");

                    b.Navigation("Price_package");

                    b.Navigation("Recipes");

                    b.Navigation("Subject_Category");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
